package inflect

var irregularRules = [][]string{
	// Pronouns.
	{"I", "we"},
	{"me", "us"},
	{"he", "they"},
	{"she", "they"},
	{"them", "them"},
	{"myself", "ourselves"},
	{"yourself", "yourselves"},
	{"itself", "themselves"},
	{"herself", "themselves"},
	{"himself", "themselves"},
	{"themself", "themselves"},
	{"is", "are"},
	{"was", "were"},
	{"has", "have"},
	{"this", "these"},
	{"that", "those"},
	// Words ending in with a consonant and `o`.
	{"echo", "echoes"},
	{"dingo", "dingoes"},
	{"volcano", "volcanoes"},
	{"tornado", "tornadoes"},
	{"torpedo", "torpedoes"},
	// Ends with `us`.
	{"genus", "genera"},
	{"viscus", "viscera"},
	// Ends with `ma`.
	{"stigma", "stigmata"},
	{"stoma", "stomata"},
	{"dogma", "dogmata"},
	{"lemma", "lemmata"},
	{"schema", "schemata"},
	{"anathema", "anathemata"},
	// Other irregular rules.
	{"ox", "oxen"},
	{"axe", "axes"},
	{"die", "dice"},
	{"yes", "yeses"},
	{"foot", "feet"},
	{"eave", "eaves"},
	{"goose", "geese"},
	{"tooth", "teeth"},
	{"quiz", "quizzes"},
	{"human", "humans"},
	{"proof", "proofs"},
	{"carve", "carves"},
	{"valve", "valves"},
	{"looey", "looies"},
	{"thief", "thieves"},
	{"groove", "grooves"},
	{"pickaxe", "pickaxes"},
	{"whiskey", "whiskies"},
}

var pluralizationRules = [][]string{
	{`/s?$/i`, `s`},
	{`/[^\u0000-\u007F]$/i`, `$0`},
	{`/([^aeiou]ese)$/i`, `$1`},
	{`/(ax|test)is$/i`, `$1es`},
	{`/(alias|[^aou]us|t[lm]as|gas|ris)$/i`, `$1es`},
	{`/(e[mn]u)s?$/i`, `$1s`},
	{`/([^l]ias|[aeiou]las|[ejzr]as|[iu]am)$/i`, `$1`},
	{`/(alumn|syllab|octop|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$/i`, `$1i`},
	{`/(alumn|alg|vertebr)(?:a|ae)$/i`, `$1ae`},
	{`/(seraph|cherub)(?:im)?$/i`, `$1im`},
	{`/(her|at|gr)o$/i`, `$1oes`},
	{`/(agend|addend|millenni|dat|extrem|bacteri|desiderat|strat|candelabr|errat|ov|symposi|curricul|automat|quor)(?:a|um)$/i`, `$1a`},
	{`/(apheli|hyperbat|periheli|asyndet|noumen|phenomen|criteri|organ|prolegomen|hedr|automat)(?:a|on)$/i`, `$1a`},
	{`/sis$/i`, `ses`},
	{`/(?:(kni|wi|li)fe|(ar|l|ea|eo|oa|hoo)f)$/i`, `$1$2ves`},
	{`/([^aeiouy]|qu)y$/i`, `$1ies`},
	{`/([^ch][ieo][ln])ey$/i`, `$1ies`},
	{`/(x|ch|ss|sh|zz)$/i`, `$1es`},
	{`/(matr|cod|mur|sil|vert|ind|append)(?:ix|ex)$/i`, `$1ices`},
	{`/\b((?:tit)?m|l)(?:ice|ouse)$/i`, `$1ice`},
	{`/(pe)(?:rson|ople)$/i`, `$1ople`},
	{`/(child)(?:ren)?$/i`, `$1ren`},
	{`/eaux$/i`, `$0`},
	{`/m[ae]n$/i`, `men`},
	{`thou`, `you`},
}

var singularizationRules = [][]string{
	{`/s$/i`, ``},
	{`/(ss)$/i`, `$1`},
	{`/(wi|kni|(?:after|half|high|low|mid|non|night|[^\w]|^)li)ves$/i`, `$1fe`},
	{`/(ar|(?:wo|[ae])l|[eo][ao])ves$/i`, `$1f`},
	{`/ies$/i`, `y`},
	{`/\b([pl]|zomb|(?:neck|cross)?t|coll|faer|food|gen|goon|group|lass|talk|goal|cut)ies$/i`, `$1ie`},
	{`/\b(mon|smil)ies$/i`, `$1ey`},
	{`/\b((?:tit)?m|l)ice$/i`, `$1ouse`},
	{`/(seraph|cherub)im$/i`, `$1`},
	{`/(x|ch|ss|sh|zz|tto|go|cho|alias|[^aou]us|t[lm]as|gas|(?:her|at|gr)o|ris)(?:es)?$/i`, `$1`},
	{`/(analy|ba|diagno|parenthe|progno|synop|the|empha|cri)(?:sis|ses)$/i`, `$1sis`},
	{`/(movie|twelve|abuse|e[mn]u)s$/i`, `$1`},
	{`/(test)(?:is|es)$/i`, `$1is`},
	{`/(alumn|syllab|octop|vir|radi|nucle|fung|cact|stimul|termin|bacill|foc|uter|loc|strat)(?:us|i)$/i`, `$1us`},
	{`/(agend|addend|millenni|dat|extrem|bacteri|desiderat|strat|candelabr|errat|ov|symposi|curricul|quor)a$/i`, `$1um`},
	{`/(apheli|hyperbat|periheli|asyndet|noumen|phenomen|criteri|organ|prolegomen|hedr|automat)a$/i`, `$1on`},
	{`/(alumn|alg|vertebr)ae$/i`, `$1a`},
	{`/(cod|mur|sil|vert|ind)ices$/i`, `$1ex`},
	{`/(matr|append)ices$/i`, `$1ix`},
	{`/(pe)(rson|ople)$/i`, `$1rson`},
	{`/(child)ren$/i`, `$1`},
	{`/(eau)x?$/i`, `$1`},
	{`/men$/i`, `man`},
}

//Uncountable rules.
var uncountableRules = []string{
	// singular words with no plurals.
	"adulthood",
	"advice",
	"agenda",
	"aid",
	"alcohol",
	"ammo",
	"anime",
	"athletics",
	"audio",
	"bison",
	"blood",
	"bream",
	"buffalo",
	"butter",
	"carp",
	"cash",
	"chassis",
	"chess",
	"clothing",
	"cod",
	"commerce",
	"cooperation",
	"corps",
	"debris",
	"diabetes",
	"digestion",
	"elk",
	"energy",
	"equipment",
	"excretion",
	"expertise",
	"flounder",
	"fun",
	"gallows",
	"garbage",
	"graffiti",
	"headquarters",
	"health",
	"herpes",
	"highjinks",
	"homework",
	"housework",
	"information",
	"jeans",
	"justice",
	"kudos",
	"labour",
	"literature",
	"machinery",
	"mackerel",
	"mail",
	"media",
	"mews",
	"moose",
	"music",
	"mud",
	"manga",
	"news",
	"pike",
	"plankton",
	"pliers",
	"police",
	"pollution",
	"premises",
	"rain",
	"research",
	"rice",
	"salmon",
	"scissors",
	"series",
	"sewage",
	"shambles",
	"shrimp",
	"species",
	"staff",
	"swine",
	"tennis",
	"traffic",
	"transportation",
	"trout",
	"tuna",
	"wealth",
	"welfare",
	"whiting",
	"wildebeest",
	"wildlife",
	"you",
	// Regexes.
	`/[^aeiou]ese$/i`, // "chinese", "japanese"
	`/deer$/i`,        // "deer", "reindeer"
	`/fish$/i`,        // "fish", "blowfish", "angelfish"
	`/measles$/i`,
	`/o[iu]s$/i`, // "carnivorous"
	`/pox$/i`,    // "chickpox", "smallpox"
	`/sheep$/i`,
}
